#!/bin/bash

TAG=$(date +"%d-%m-%Y")
docker build -t stripe/example-terminal-backend:$TAG .
docker build -t stripe/example-terminal-backend:latest .

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push stripe/example-terminal-backend:$TAG
docker push stripe/example-terminal-backend:latest
